//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmniaGUI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point Main_Window_Location {
            get {
                return ((global::System.Drawing.Point)(this["Main_Window_Location"]));
            }
            set {
                this["Main_Window_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point S_meter_Location {
            get {
                return ((global::System.Drawing.Point)(this["S_meter_Location"]));
            }
            set {
                this["S_meter_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point Panadapter_Location {
            get {
                return ((global::System.Drawing.Point)(this["Panadapter_Location"]));
            }
            set {
                this["Panadapter_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point Panadapter_Control_Location {
            get {
                return ((global::System.Drawing.Point)(this["Panadapter_Control_Location"]));
            }
            set {
                this["Panadapter_Control_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size Panadapter_Size {
            get {
                return ((global::System.Drawing.Size)(this["Panadapter_Size"]));
            }
            set {
                this["Panadapter_Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point Waterfall_Location {
            get {
                return ((global::System.Drawing.Point)(this["Waterfall_Location"]));
            }
            set {
                this["Waterfall_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size Waterfall_Size {
            get {
                return ((global::System.Drawing.Size)(this["Waterfall_Size"]));
            }
            set {
                this["Waterfall_Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting {
            get {
                return ((string)(this["Setting"]));
            }
            set {
                this["Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size Main_Window_Size {
            get {
                return ((global::System.Drawing.Size)(this["Main_Window_Size"]));
            }
            set {
                this["Main_Window_Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color Background_Color {
            get {
                return ((global::System.Drawing.Color)(this["Background_Color"]));
            }
            set {
                this["Background_Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color Freq_Color {
            get {
                return ((global::System.Drawing.Color)(this["Freq_Color"]));
            }
            set {
                this["Freq_Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Docked {
            get {
                return ((bool)(this["Docked"]));
            }
            set {
                this["Docked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte Autodocked {
            get {
                return ((byte)(this["Autodocked"]));
            }
            set {
                this["Autodocked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte Top_Window {
            get {
                return ((byte)(this["Top_Window"]));
            }
            set {
                this["Top_Window"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color Boarder_Color {
            get {
                return ((global::System.Drawing.Color)(this["Boarder_Color"]));
            }
            set {
                this["Boarder_Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Auto_Zero {
            get {
                return ((bool)(this["Auto_Zero"]));
            }
            set {
                this["Auto_Zero"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Band_Change_Tune {
            get {
                return ((bool)(this["Band_Change_Tune"]));
            }
            set {
                this["Band_Change_Tune"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color Waterfall_Marker {
            get {
                return ((global::System.Drawing.Color)(this["Waterfall_Marker"]));
            }
            set {
                this["Waterfall_Marker"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Waterfall_Marker_Color_Index {
            get {
                return ((int)(this["Waterfall_Marker_Color_Index"]));
            }
            set {
                this["Waterfall_Marker_Color_Index"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RIT_Step {
            get {
                return ((int)(this["RIT_Step"]));
            }
            set {
                this["RIT_Step"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RIT_Limits {
            get {
                return ((int)(this["RIT_Limits"]));
            }
            set {
                this["RIT_Limits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Mic_Is_Digital {
            get {
                return ((bool)(this["Mic_Is_Digital"]));
            }
            set {
                this["Mic_Is_Digital"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public short Digital_Volume {
            get {
                return ((short)(this["Digital_Volume"]));
            }
            set {
                this["Digital_Volume"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public short Voice_Volume {
            get {
                return ((short)(this["Voice_Volume"]));
            }
            set {
                this["Voice_Volume"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Stop_Server {
            get {
                return ((bool)(this["Stop_Server"]));
            }
            set {
                this["Stop_Server"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte Antenna_Switch {
            get {
                return ((byte)(this["Antenna_Switch"]));
            }
            set {
                this["Antenna_Switch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte Antenna_Switch_Index {
            get {
                return ((byte)(this["Antenna_Switch_Index"]));
            }
            set {
                this["Antenna_Switch_Index"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Hi_Cut_Default {
            get {
                return ((int)(this["Hi_Cut_Default"]));
            }
            set {
                this["Hi_Cut_Default"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Lo_Cut_Default {
            get {
                return ((int)(this["Lo_Cut_Default"]));
            }
            set {
                this["Lo_Cut_Default"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CW_Default {
            get {
                return ((int)(this["CW_Default"]));
            }
            set {
                this["CW_Default"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public short Mic_Gain_Step {
            get {
                return ((short)(this["Mic_Gain_Step"]));
            }
            set {
                this["Mic_Gain_Step"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SWR_Meter_Hold {
            get {
                return ((int)(this["SWR_Meter_Hold"]));
            }
            set {
                this["SWR_Meter_Hold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Time_Check_Box {
            get {
                return ((bool)(this["Time_Check_Box"]));
            }
            set {
                this["Time_Check_Box"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public byte Meter_Mode {
            get {
                return ((byte)(this["Meter_Mode"]));
            }
            set {
                this["Meter_Mode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Volume_Attn_Index {
            get {
                return ((int)(this["Volume_Attn_Index"]));
            }
            set {
                this["Volume_Attn_Index"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public short Time_Grid {
            get {
                return ((short)(this["Time_Grid"]));
            }
            set {
                this["Time_Grid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Speaker_MutED {
            get {
                return ((bool)(this["Speaker_MutED"]));
            }
            set {
                this["Speaker_MutED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gainsboro")]
        public global::System.Drawing.Color Control_Backgroud_Color {
            get {
                return ((global::System.Drawing.Color)(this["Control_Backgroud_Color"]));
            }
            set {
                this["Control_Backgroud_Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color Control_Foreground_Color {
            get {
                return ((global::System.Drawing.Color)(this["Control_Foreground_Color"]));
            }
            set {
                this["Control_Foreground_Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Meter_Peak_Needle {
            get {
                return ((bool)(this["Meter_Peak_Needle"]));
            }
            set {
                this["Meter_Peak_Needle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte Meter_Peak_Hold {
            get {
                return ((byte)(this["Meter_Peak_Hold"]));
            }
            set {
                this["Meter_Peak_Hold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte Meter_Peak_Needle_Color {
            get {
                return ((byte)(this["Meter_Peak_Needle_Color"]));
            }
            set {
                this["Meter_Peak_Needle_Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Speaker_Volume {
            get {
                return ((int)(this["Speaker_Volume"]));
            }
            set {
                this["Speaker_Volume"] = value;
            }
        }
    }
}
